name: Lint

on: [pull_request]

jobs:
  misspell:
    name: Check Spelling Misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -i 'aircrafts,devels,invertions' -error
